global using Microsoft.Data.Sqlite;
global using Microsoft.EntityFrameworkCore;
global using MediatR;
global using Rocks;
global using Atoms.Core.Data;
global using Atoms.Core.Entities;
global using Atoms.Core.Enums;
global using Atoms.Core.Interfaces;
global using Atoms.Core.AI.Strategies;
global using static Atoms.Core.Entities.Game.GameBoard;
