global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Options;
global using Atoms.Core;
global using Atoms.Core.DTOs;
global using Atoms.Core.Entities;
global using Atoms.Core.Entities.Configuration;
global using Atoms.Core.Enums;
global using Atoms.Core.Interfaces;
global using Atoms.Core.ValueObjects;
