// <auto-generated />
using System;
using System.Collections.Generic;
using Atoms.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Atoms.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Atoms.Core.DTOs.GameDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AtomShape")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColourScheme")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalStorageUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Move")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("Board", "Atoms.Core.DTOs.GameDTO.Board#BoardDTO", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Data")
                                .IsRequired()
                                .HasColumnType("TEXT");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Rng", "Atoms.Core.DTOs.GameDTO.Rng#RngDTO", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Iterations")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Seed")
                                .HasColumnType("INTEGER");
                        });

                    b.HasKey("Id");

                    b.HasIndex("LastUpdatedDateUtc");

                    b.HasIndex("LocalStorageUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Atoms.Core.DTOs.GameInfoDTO", b =>
                {
                    b.Property<DateTime>("CreatedDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdatedDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Move")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Opponents")
                        .HasColumnType("TEXT");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Winner")
                        .HasColumnType("TEXT");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Atoms.Core.DTOs.LocalStorageUserDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LocalStorageUsers");
                });

            modelBuilder.Entity("Atoms.Core.DTOs.PlayerDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AbbreviatedName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteCode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LocalStorageUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("IsWinner");

                    b.HasIndex("LocalStorageUserId");

                    b.HasIndex("PlayerTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Atoms.Core.DTOs.PlayerTypeDTO", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlayerTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Human",
                            Name = "Human"
                        },
                        new
                        {
                            Id = 2,
                            Description = "CPU (Easy)",
                            Name = "CPU (E)"
                        },
                        new
                        {
                            Id = 3,
                            Description = "CPU (Medium)",
                            Name = "CPU (M)"
                        },
                        new
                        {
                            Id = 4,
                            Description = "CPU (Hard)",
                            Name = "CPU (H)"
                        });
                });

            modelBuilder.Entity("Atoms.Core.DTOs.GameDTO", b =>
                {
                    b.HasOne("Atoms.Core.DTOs.LocalStorageUserDTO", "LocalStorageUser")
                        .WithMany("Games")
                        .HasForeignKey("LocalStorageUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocalStorageUser");
                });

            modelBuilder.Entity("Atoms.Core.DTOs.PlayerDTO", b =>
                {
                    b.HasOne("Atoms.Core.DTOs.GameDTO", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atoms.Core.DTOs.LocalStorageUserDTO", "LocalStorageUser")
                        .WithMany("Players")
                        .HasForeignKey("LocalStorageUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Atoms.Core.DTOs.PlayerTypeDTO", "PlayerType")
                        .WithMany()
                        .HasForeignKey("PlayerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("LocalStorageUser");

                    b.Navigation("PlayerType");
                });

            modelBuilder.Entity("Atoms.Core.DTOs.GameDTO", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Atoms.Core.DTOs.LocalStorageUserDTO", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
